server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: movie-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Zipkin (opcional)
management:
  tracing:
    sampling:
      probability: 1.0

internal:
  api-key: ${INTERNAL_API_KEY:CHANGE_ME}

# TMDB API (v3: api_key en query; v4: usar tmdb.use-bearer-auth: true y token como Bearer)
tmdb:
  base-url: https://api.themoviedb.org/3
  api-key: ${TMDB_API_KEY:}
  language: es-ES
  # use-bearer-auth: true   # descomenta si usas token de lectura v4 (Authorization: Bearer)
