server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: movie-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Zipkin (opcional)
management:
  tracing:
    sampling:
      probability: 1.0

internal:
  api-key: ${INTERNAL_API_KEY:CHANGE_ME}

# TMDB API
# - v3: API Key (32 caracteres) → deja use-bearer-auth: false
# - v4: API Read Access Token (largo) → pon use-bearer-auth: true o tendrás "Invalid API key"
tmdb:
  base-url: https://api.themoviedb.org/3
  api-key: ${TMDB_API_KEY:}
  language: es-ES
  use-bearer-auth: true   # true = token v4 (Bearer). Si usas API Key v3, cambia a false
