server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: movie-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# Zipkin (opcional)
management:
  tracing:
    sampling:
      probability: 1.0

internal:
  api-key: ${INTERNAL_API_KEY:CHANGE_ME}
